kafka:
  topic: kafka-test
server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 192.168.56.101:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: springboot-groupid
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer #key的序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #value的序列化
      transaction-id-prefix: test_tx_   #开启事务
  swagger2:
    enabled: true