server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/micromall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
        enabled: true #是否启用StatFilter默认值false
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
        enabled: true # 默认关闭了管理面
      filter:
        config:
          enabled: true

  data:
    elasticsearch:
      repositories:
        enabled: true
#      cluster-nodes: 192.168.56.101:9300
#      cluster-name: elasticsearch
      client:
        reactive:
          endpoints: 192.168.56.101:9200
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml




