spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
    alicloud:
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: ithawk

  application:
    name: gulimall-third-party

server:
  port: 30000
