spring:
  profiles:
    active: pg
#是否开启缓存，开发时可设置为false，默认为true
  thymeleaf:
    cache: false
  #检查模版是否存在，默认为true
    check-template: true
  #检查模版位置是否存在，默认为true
    check-template-location: true
  #模版文件编码
    encoding: UTF-8
  #模版文件位置
    prefix: classpath:/template/
  #Content-Type配置
    servlet:
      content-type: text/html
  #模版文件后缀
    suffix: .html