spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.56.101:8848
      config:
        server-addr: http://192.168.56.101:8848
        namespace: 1986f4f3-69e0-43bb-859c-abe427b19f3a
        file-extension: yaml

