server:
  port: 8000

spring:
  application:
    name: springboot-skywalking-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/code/codeMake
    username: sa
    password:

