logging:
  config: classpath:log4j.xml
  level:
    cn.jay.repository: trace
    com.tj.mapper: trace
spring:
  elasticsearch:
    rest:
      uris:
        - http://127.0.0.1:9200
      test: 122
      urls: http://127.0.0.1:9200,http://127.0.0.1:9201