DROP TABLE IF EXISTS public.USER;
-- 设置自增索引
-- UNIQUE 设置唯一约束
CREATE TABLE public.USER
(
    ID                     VARCHAR(32) NOT NULL PRIMARY KEY ,
    PARENT_ID              VARCHAR(32) NOT NULL ,
    NAME                   VARCHAR(32) NOT NULL ,
    INFANT_NAME            VARCHAR(32) ,
    COURTESY_NAME          VARCHAR(32)  ,
    PSEUDONYM              VARCHAR(32)  ,
    SCHOOLING              VARCHAR(32) NOT NULL ,
    EMAIL                  VARCHAR(200) NOT NULL ,
    PHONE_NUMBER           VARCHAR(15) NOT NULL ,
    STATUS                 INT2        NOT NULL DEFAULT 1,
    BIRTH_DAY              DATE        NOT NULL ,
    DEAD_DAY               DATE        ,
    DEAD_PLACE             VARCHAR(500) ,
    CREATE_TIME            DATE        NOT NULL DEFAULT NOW(),
    LAST_UPDATE_TIME       DATE        NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.USER IS '用户表';
COMMENT ON COLUMN public.USER.ID IS '用户id';
COMMENT ON COLUMN public.USER.ID IS '父Id';
COMMENT ON COLUMN public.USER.NAME IS '用户名';
COMMENT ON COLUMN public.USER.INFANT_NAME IS '乳名';
COMMENT ON COLUMN public.USER.COURTESY_NAME IS '字';
COMMENT ON COLUMN public.USER.PSEUDONYM IS '号';
COMMENT ON COLUMN public.USER.SCHOOLING IS '学历';
COMMENT ON COLUMN public.USER.EMAIL IS '邮箱';
COMMENT ON COLUMN public.USER.PHONE_NUMBER IS '手机号码';
COMMENT ON COLUMN public.USER.STATUS IS '状态，-1：逻辑删除，0：禁用，1：启用';
COMMENT ON COLUMN public.USER.BIRTH_DAY IS '出生日期';
COMMENT ON COLUMN public.USER.DEAD_DAY IS '死亡日期';
COMMENT ON COLUMN public.USER.DEAD_PLACE IS '埋葬地点';
COMMENT ON COLUMN public.USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN public.USER.LAST_UPDATE_TIME IS '上次更新时间';


DROP TABLE IF EXISTS public.USER_EVENT;
-- 设置自增索引
-- UNIQUE 设置唯一约束
CREATE SEQUENCE USER_event_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE TABLE public.USER
(
    ID                  INT4        NOT NULL PRIMARY KEY DEFAULT nextval('USER_event_seq'),
    USER_ID             VARCHAR(32) NOT NULL ,
    EVENT_DES           VARCHAR(2000) NOT NULL,
    EVENT_TYPE          VARCHAR(32) NOT NULL ,
    INFLUENCE           VARCHAR(32) NOT NULL ,
    STATUS              INT2        NOT NULL DEFAULT 1,
    START_TIME          DATE        NOT NULL DEFAULT NOW(),
    END_TIME            DATE        NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.USER IS '用户表事件';
COMMENT ON COLUMN public.USER.ID IS '事件ID';
COMMENT ON COLUMN public.USER.USER_ID IS '用户名ID';
COMMENT ON COLUMN public.USER.EVENT_DES IS '事件描述';
COMMENT ON COLUMN public.USER.EVENT_TYPE IS '事件类型';
COMMENT ON COLUMN public.USER.INFLUENCE IS '事件影响';
COMMENT ON COLUMN public.USER.STATUS IS '状态，-1：逻辑删除，0：禁用，1：启用';
COMMENT ON COLUMN public.USER.START_TIME IS '开始时间';
COMMENT ON COLUMN public.USER.END_TIME IS '结束时间';