server:
  port: 8081

# 设置Spring-Data-JPA
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 111

# 配置日志
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    # 以下两种设置的前提都是show-sql: true
    # 显示动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 显示查询结果（如果是查询的话）
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc.provider: debug
