DROP TABLE IF EXISTS public.ORM_USER;
-- 设置自增索引
-- UNIQUE 设置唯一约束
CREATE SEQUENCE orm_user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE TABLE public.ORM_USER
(
    ID               INT4        NOT NULL PRIMARY KEY DEFAULT nextval('orm_user_id_seq'),
    NAME             VARCHAR(32) NOT NULL ,
    PASSWORD         VARCHAR(32) NOT NULL,
    SALT             VARCHAR(32) NOT NULL ,
    EMAIL            VARCHAR(32) NOT NULL UNIQUE,
    PHONE_NUMBER     VARCHAR(15) NOT NULL UNIQUE,
    STATUS           INT2        NOT NULL DEFAULT 1,
    CREATE_TIME      DATE        NOT NULL DEFAULT NOW(),
    LAST_LOGIN_TIME  DATE        NOT NULL DEFAULT NOW(),
    LAST_UPDATE_TIME DATE        NOT NULL DEFAULT NOW()
);
-- ALTER TABLE public.ORM_USER ALTER COLUMN ID SET DEFAULT nextval('orm_user_id_seq');
COMMENT ON TABLE public.ORM_USER IS '用户表';
COMMENT ON COLUMN public.ORM_USER.ID IS '用户id';
COMMENT ON COLUMN public.ORM_USER.NAME IS '用户名';
COMMENT ON COLUMN public.ORM_USER.PASSWORD IS '加密后的密码';
COMMENT ON COLUMN public.ORM_USER.SALT IS '加密使用的盐';
COMMENT ON COLUMN public.ORM_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN public.ORM_USER.PHONE_NUMBER IS '手机号码';
COMMENT ON COLUMN public.ORM_USER.STATUS IS '状态，-1：逻辑删除，0：禁用，1：启用';
COMMENT ON COLUMN public.ORM_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN public.ORM_USER.LAST_LOGIN_TIME IS '上次登录时间';
COMMENT ON COLUMN public.ORM_USER.LAST_UPDATE_TIME IS '上次更新时间';

DROP TABLE IF EXISTS public.SHARE_EMAIL_DETAIL;
-- 设置自增索引
-- UNIQUE 设置唯一约束
CREATE SEQUENCE share_email_detail_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE TABLE public.SHARE_EMAIL_DETAIL
(
    ID               INT4        NOT NULL PRIMARY KEY DEFAULT nextval('share_email_detail_id_seq'),
    NAME             VARCHAR(32) NOT NULL ,
    CREATOR          VARCHAR(50) NOT NULL,
    CREATE_TIME      DATE        NOT NULL DEFAULT NOW() ,
    EMAIL_DATA       VARCHAR(6000) NOT NULL ,
    RECEIVERS        VARCHAR(6000) NOT NULL ,
    CONTENT          VARCHAR(6000)        NOT NULL ,
    SUBJECT          VARCHAR(6000)        NOT NULL ,
    STATUS           INT2        NOT NULL DEFAULT 1,
    LAST_UPDATE_TIME DATE        NOT NULL DEFAULT NOW(),
    SEND_TYPE        VARCHAR(32)        NOT NULL DEFAULT 'CARD'
);
-- ALTER TABLE public.ORM_USER ALTER COLUMN ID SET DEFAULT nextval('orm_user_id_seq');
COMMENT ON TABLE public.SHARE_EMAIL_DETAIL IS '分享邮件详情表';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.ID IS 'id';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.NAME IS '邮件名';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.CREATOR IS '邮件发送者';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.CREATE_TIME IS '邮件创建时间';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.EMAIL_DATA IS '邮件内容';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.RECEIVERS IS '邮件接收者';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.STATUS IS '状态，-1：邮件发送失败，0：邮件未发，1：邮件发送成功';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.CONTENT IS '邮件内容';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.SUBJECT IS '邮件主题';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.LAST_UPDATE_TIME IS '上次更新时间';
COMMENT ON COLUMN public.SHARE_EMAIL_DETAIL.SEND_TYPE IS '邮件发送模式';
