#logging:
#  config: classpath:log4j.xml
#  level:
#    cn.jay.repository: trace
server:
  port: 8088
spring:
  profiles:
    active: h2
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 关闭缓存
    cache: false
management:
  endpoints:
    web:
       exposure:
         include: '*'
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.ithawk.mgr.dao



