server:
  port: 18090
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: gulimall-search
  elasticsearch:
    rest:
      uris:
        - http://192.168.56.101:9200
management:
  endpoints:
    web:
      exposure:
        include: "*"