server:
  port: 8081

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/test
    username: root
    password: 123456

  application:
    name: abcmsc-provider-depart

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8000/eureka



