DROP TABLE IF EXISTS public.ORM_USER;
-- 设置自增索引
-- UNIQUE 设置唯一约束
CREATE SEQUENCE orm_user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE TABLE public.ORM_USER
(
    ID               INT4        NOT NULL PRIMARY KEY DEFAULT nextval('orm_user_id_seq'),
    NAME             VARCHAR(32) NOT NULL ,
    PASSWORD         VARCHAR(32) NOT NULL,
    SALT             VARCHAR(32) NOT NULL ,
    EMAIL            VARCHAR(32) NOT NULL UNIQUE,
    PHONE_NUMBER     VARCHAR(15) NOT NULL UNIQUE,
    STATUS           INT2        NOT NULL DEFAULT 1,
    CREATE_TIME      DATE        NOT NULL DEFAULT NOW(),
    LAST_LOGIN_TIME  DATE        NOT NULL DEFAULT NOW(),
    LAST_UPDATE_TIME DATE        NOT NULL DEFAULT NOW()
);
-- ALTER TABLE public.ORM_USER ALTER COLUMN ID SET DEFAULT nextval('orm_user_id_seq');
COMMENT ON TABLE public.ORM_USER IS '用户表';
COMMENT ON COLUMN public.ORM_USER.ID IS '用户id';
COMMENT ON COLUMN public.ORM_USER.NAME IS '用户名';
COMMENT ON COLUMN public.ORM_USER.PASSWORD IS '加密后的密码';
COMMENT ON COLUMN public.ORM_USER.SALT IS '加密使用的盐';
COMMENT ON COLUMN public.ORM_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN public.ORM_USER.PHONE_NUMBER IS '手机号码';
COMMENT ON COLUMN public.ORM_USER.STATUS IS '状态，-1：逻辑删除，0：禁用，1：启用';
COMMENT ON COLUMN public.ORM_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN public.ORM_USER.LAST_LOGIN_TIME IS '上次登录时间';
COMMENT ON COLUMN public.ORM_USER.LAST_UPDATE_TIME IS '上次更新时间';
