server:
  port: 8081
  servlet:
    context-path: /ipfs
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 关闭缓存
    cache: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    schema: classpath:db/schema.sql     #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    #    data: classpath:db/data.sql     #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
    platform: h2
  h2:   # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
    console:
      settings:
        web-allow-others: true
      path: /h2       #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      enabled: true        #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
logging:
  level:
    com.com.ithawk: debug
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ithawk.demo.springboot.thymeleaf.model
ipfs:
  downloadBaseUrl: http://127.0.0.1:${server.port}/ipfs/downloadFile
  ipfsIp: 127.0.0.1
  ipfsPort: 15001
system:
  localPath: C:/mydata/
#以太坊交互地址 如果以太坊环境搭建在本地就locallhost,否则使用对应的ip地址，端口默认使用8545
web3j:
  client-address: http://localhost:9545