server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: 192.168.101.150
    port: 5672
    username: demo
    password: demo
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual